name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-iris
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: flake8

      - name: Tests
        run: pytest -q

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_REPO:${{ steps.vars.outputs.TAG }} -t $DOCKERHUB_REPO:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $DOCKERHUB_REPO:${{ steps.vars.outputs.TAG }}
          docker push $DOCKERHUB_REPO:latest